include(FetchContent)

set(MI_OVERRIDE OFF CACHE BOOL "MI_OVERRIDE")
set(MI_NO_USE_CXX ON CACHE BOOL "MI_NO_USE_CXX")
set(MI_BUILD_TESTS OFF CACHE BOOL "MI_BUILD_TESTS")
set(MI_BUILD_OBJECT OFF CACHE BOOL "MI_BUILD_OBJECT")
set(MI_BUILD_SHARED OFF CACHE BOOL "MI_BUILD_SHARED")
set(MI_BUILD_STATIC ON CACHE BOOL "MI_BUILD_STATIC")
set(MI_SECURE OFF CACHE BOOL "MI_SECURE")
set(MI_PADDING OFF CACHE BOOL "MI_PADDDING")
set(MI_DEBUG_FULL OFF CACHE BOOL "MI_DEBUG_FULL")

FetchContent_Declare(
        mimalloc
        GIT_REPOSITORY https://github.com/microsoft/mimalloc.git
        GIT_TAG main
)
FetchContent_MakeAvailable(mimalloc)
