include(FetchContent)

set(SDL_SHARED ON CACHE BOOL "SDL_SHARED")
set(SDL_STATIC OFF CACHE BOOL "SDL_STATIC")
set(SDL_TEST_LIBRARY OFF CACHE BOOL "SDL_TEST_LIBRARY")
set(SDL_TESTS OFF CACHE BOOL "SDL_TESTS")
set(SDL_EXAMPLES OFF CACHE BOOL "SDL_EXAMPLES")
set(SDL_DISABLE_INSTALL ON CACHE BOOL "SDL_DISABLE_INSTALL")

set(SDL_CAMERA OFF CACHE BOOL "SDL_CAMERA")
set(SDL_GPU OFF CACHE BOOL "SDL_GPU")
set(SDL_RENDER OFF CACHE BOOL "SDL_RENDER")
set(SDL_JOYSTICK OFF CACHE BOOL "SDL_JOYSTICK")
set(SDL_HAPTIC OFF CACHE BOOL "SDL_HAPTIC")
set(SDL_HIDAPI OFF CACHE BOOL "SDL_HIDAPI")
set(SDL_POWER OFF CACHE BOOL "SDL_POWER")
set(SDL_SENSOR OFF CACHE BOOL "SDL_SENSOR")

set(SDL_OFFSCREEN OFF CACHE BOOL "SDL_OFFSCREEN")
set(SDL_OPENGL OFF CACHE BOOL "SDL_OPENGL")
set(SDL_OPENGLES OFF CACHE BOOL "SDL_OPENGLES")

FetchContent_Declare(
        SDL3
        GIT_REPOSITORY https://github.com/libsdl-org/SDL.git
        GIT_TAG main
        GIT_SHALLOW TRUE
        DOWNLOAD_EXTRACT_TIMESTAMP ON
        CMAKE_ARGS -DSDL_SHARED=ON -DSDL_STATIC=OFF -DSDL_TEST_LIBRARY=OFF -DSDL_TESTS=OFF -DSDL_EXAMPLES=OFF
)
FetchContent_MakeAvailable(SDL3)
