include(FetchContent)

set(VULKAN_HEADERS_ENABLE_TESTS OFF CACHE BOOL "VULKAN_HEADERS_ENABLE_TESTS")
set(VULKAN_HEADERS_ENABLE_INSTALL OFF CACHE BOOL "VULKAN_HEADERS_ENABLE_INSTALL")

FetchContent_Declare(
        VULKAN_HEADERS
        GIT_REPOSITORY https://github.com/KhronosGroup/Vulkan-Headers.git
        GIT_TAG main
        CMAKE_ARGS -DVULKAN_HEADERS_ENABLE_TESTS=OFF -DVULKAN_HEADERS_ENABLE_INSTALL=OFF
        GIT_SHALLOW TRUE
)
FetchContent_MakeAvailable(VULKAN_HEADERS)